### ISSUE TITLE
Humo app links appear as movies

### ISSUE THREAD

**Issue by francisdb** [francisdb/belgiantv#35]
Looks like the moved their api: `Download onze nieuwe app!`

<img width="763" alt="image" src="https://user-images.githubusercontent.com/161305/73523457-3869ac80-440b-11ea-9958-5b3feda34c3e.png">

**Comment by WimObiwan** [comment]
Their original API located at
https://www.humo.be/api/epg/humosite/schedule/main/2020-02-01
seems disabled since last night.

It seems they now have a newer one locate at:
https://www.humo.be/tv-gids/api/v2/broadcasts/2020-02-01

**Comment by francisdb** [comment]
@WimObiwan thanks for the pointer, will try to fix this somewhere next week

**Comment by francisdb** [comment]
Looks like you also posted here and they have done some more investigations:
https://github.com/tvgrabbers/tvgrabpyAPI/issues/46
